trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  artifactName: 'NuGet'

stages:
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    steps:
    - script: |
        dotnet build HumbleMediator.sln --configuration $(buildConfiguration)
      displayName: 'Build ($(buildConfiguration))'
    - script: |
        dotnet test HumbleMediator.sln \
          --configuration $(buildConfiguration) \
          --no-build \
          --verbosity Normal \
          --logger trx
      displayName: 'Run tests'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
      displayName: 'Publish test results'
    - script: |
        dotnet pack ./src/HumbleMediator.csproj \
          -c $(buildConfiguration) \
          --include-symbols \
          --no-build \
          -o $(Build.ArtifactStagingDirectory)
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
      displayName: 'Create build artifact'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: $(artifactName)
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
      displayName: 'Publish artifacts'
    - task: NuGetAuthenticate@1
      displayName: 'NuGet authenticate'
    - script: |
        nuget push $(Build.ArtifactStagingDirectory)/*.nupkg \
        -ApiKey az \
        -Source $(NUGET_CI_FEED)
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
      displayName: 'Push to CI NuGet feed'

