trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
  displayName: 'Install sdk 6.0.x'
# Build and test
- script: |
    dotnet build HumbleMediator.sln --configuration $(buildConfiguration)
  displayName: 'Build ($(buildConfiguration))'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    configuration: '$(buildConfiguration)'