trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
  displayName: 'Install sdk 6.0.x'
# Build and test
- script: |
    dotnet build HumbleMediator.sln --configuration $(buildConfiguration)
  displayName: 'Build ($(buildConfiguration))'
- script: |
    dotnet test HumbleMediator.sln \
      --configuration $(buildConfiguration) \
      --no-build \
      --verbosity Normal \
      --logger trx
  displayName: 'Run tests'
# Publish results
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'Publish test results'
