trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: BuildAndTest
  jobs:
  - job: BuildAndTestJob
    steps:
    - script: |
        dotnet build HumbleMediator.sln --configuration $(buildConfiguration)
      displayName: 'Build ($(buildConfiguration))'
    - script: |
        dotnet test HumbleMediator.sln \
          --configuration $(buildConfiguration) \
          --no-build \
          --verbosity Normal \
          --logger trx
      displayName: 'Run tests'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
      displayName: 'Publish test results'
    - script: |
        dotnet pack ./src/HumbleMediator.csproj \
          -c $(buildConfiguration) \
          --include-symbols \
          --no-build \
          -o $(Build.ArtifactStagingDirectory)
      displayName: 'Create build artifact'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: NuGet

